import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/redux/store/StoreProvider";
import { ToastContainer } from "react-toastify";
import { AuthSessionProvider } from "@/components/AuthSessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <AuthSessionProvider>
        <StoreProvider> {children} </StoreProvider>
        </AuthSessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
